### ISSUE TITLE
IE Error - Attempted to assign to readonly property - in strict mode

### ISSUE THREAD

**Issue by michi-z** [Actiview/module-honeypot#1]
Look for https://stackoverflow.com/questions/24906279/how-to-set-element-style-property-in-strict-mode. Error in IMHO in view/frontend/web/js/model/honeypot.js Zeile 33.

**Comment by rikwillems** [comment]
Thank you @michi-z for your feedback and instructions. I updated the module and tagged a new release.

**Comment by michi-z** [comment]
Thx for the quick implementation.
